// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apn_promise_recruiting_task.Model;

#nullable disable

namespace apn_promise_recruiting_task.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210184435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("apn_promise_recruiting_task.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("apn_promise_recruiting_task.Model.OrderITem", b =>
                {
                    b.Property<int>("OrderITemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderITemId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderITems");
                });

            modelBuilder.Entity("apn_promise_recruiting_task.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("apn_promise_recruiting_task.Model.Order", b =>
                {
                    b.HasOne("apn_promise_recruiting_task.Model.Order", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderId1");
                });

            modelBuilder.Entity("apn_promise_recruiting_task.Model.OrderITem", b =>
                {
                    b.HasOne("apn_promise_recruiting_task.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("apn_promise_recruiting_task.Model.Order", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
